from pydantic import BaseModel, Field
from typing import List, Optional

# File Definition
class File(BaseModel):
    """
    Represents a file to be created or modified in the project.
    """
    path: str = Field(
        ...,
        description="The relative path of the file to be created or modified"
    )
    purpose: str = Field(
        ...,
        description=(
            "The purpose of the file. "
            "Example: main application logic, data processing module, "
            "pipeline, global CSS, configuration, etc."
        )
    )

# High-Level Plan
class Plan(BaseModel):
    """
    High-level application plan produced by the planner agent.
    """
    name: str = Field(
        ...,
        description="The name of the application to be built"
    )

    description: str = Field(
        ...,
        description=(
            "A one-line description of the application. "
            "Example: 'A web application for managing personal projects'"
        )
    )

    techstack: str = Field(
        ...,
        description=(
            "Technology stack to be used. "
            "Example: Python, HTML, CSS, JavaScript, React, Flask, FastAPI"
        )
    )

    features: List[str] = Field(
        ...,
        description=(
            "List of features the application should support. "
            "Example: user authentication, dashboards, API integration"
        )
    )

    files: List[File] = Field(
        ...,
        description="List of files to be created along with their purposes"
    )

# Implementation-Level Tasks
class ImplementationTask(BaseModel):
    """
    A single implementation step for the coder agent.
    """
    filepath: str = Field(
        ...,
        description="The file path that needs to be created or modified"
    )

    task_description: str = Field(
        ...,
        description=(
            "Detailed description of the task to be performed. "
            "Example: add authentication logic, create landing page UI, "
            "implement API integration, etc."
        )
    )


class TaskPlan(BaseModel):
    """
    Ordered list of implementation steps generated by the architect agent.
    """
    implementation_steps: List[ImplementationTask] = Field(
        ...,
        description="Sequential steps required to implement the application"
    )


# Coder Output — the model's response for a single implementation step.
# Deliberately plain (no tool-calling): the coder step reads existing file
# content itself in Python and writes the result itself, so the model only
# ever needs to answer with content, never invoke anything. This sidesteps
# a broken multi-turn tool-calling path on some OpenAI-compatible gateways.
class FileContent(BaseModel):
    """
    The complete content of the file being implemented for the current step.
    """
    content: str = Field(
        ...,
        description="The full, complete content to write to the target file"
    )


# Coder Runtime State
class CoderState(BaseModel):
    """
    Mutable runtime state for the coder agent while iterating through tasks.
    """
    task_plan: TaskPlan = Field(
        ...,
        description="The task plan being executed"
    )

    project_root: str = Field(
        ...,
        description="Absolute path to this project's root directory"
    )

    current_step_idx: int = Field(
        0,
        description="Index of the current implementation step"
    )

    current_file_content: Optional[str] = Field(
        None,
        description="Current content of the file being edited"
    )
